Teamo\User\Domain\Model\User\User:
  type: entity
  repositoryClass: Teamo\User\Infrastructure\Persistence\Doctrine\DoctrineUserRepository
  table: users
  id:
    userId:
      type: UserId
      column: id
  fields:
    name:
      type: string
    email:
      type: string
    password:
      type: string
    rememberToken:
      type: string
      nullable: true
  embedded:
    preferences:
      class: Preferences
    notifications:
      class: Notifications
    avatar:
      class: Avatar
