Teamo\Project\Domain\Model\Project\Event\EventComment:
  type: entity
  repositoryClass: Teamo\Project\Infrastructure\Persistence\Doctrine\DoctrineEventCommentRepository
  table: event_comments
  id:
    commentId:
      type: CommentId
      column: id
  fields:
    eventId:
      type: EventId
    author:
      type: TeamMemberId
      column: author_team_member_id
    content:
      type: text
    attachments:
      type: AttachmentCollection
    createdOn:
      type: DateTimeImmutable
      nullable: false
    updatedOn:
      type: DateTimeImmutable
      nullable: false
